### ISSUE TITLE
NOT-3 create empty component

### ISSUE THREAD

**Issue by valentinaconde** [valentinaconde/notesApp#5]
If there are no notes, show an empty component with a message. For example, 'There are no notes now.' The message has to be passed through props

**Comment by valentinaconde** [comment]
![Image](https://github.com/user-attachments/assets/1a80ee78-f7d5-4622-a582-b105fcb578b8)

Se finalizo la tarea.

**Comment by jonathanduran7** [comment]
se cierra la tarea ya que se encuentra en main. Muchas gracias por leer

**Comment by valentinaconde** [comment]
de nada
